# Generated by Django 4.1.7 on 2023-03-01 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_booking_booking_id_alter_booking_no_of_guests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_id',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='menu_id',
        ),
    ]
